using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using DrWario.Runtime;

namespace DrWario.Editor.Analysis
{
    public static class HtmlReportBuilder
    {
        public static string Build(DiagnosticReport report, ProfilingSession session)
        {
            var sb = new StringBuilder();

            var date = report.GeneratedAt.ToString("yyyy-MM-dd HH:mm:ss");
            var duration = (report.Session.EndTime - report.Session.StartTime).TotalSeconds;

            sb.Append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>DrWario Report - ");
            sb.Append(Esc(date));
            sb.Append("</title>\n");
            AppendStyles(sb);
            sb.Append("</head>\n<body>\n");

            // Header
            sb.Append("<div class=\"header\">\n");
            sb.Append("<h1>DrWario Diagnostic Report</h1>\n");
            sb.Append("<table class=\"meta-table\">\n");
            MetaRow(sb, "Generated", date);
            MetaRow(sb, "Platform", Esc(report.Session.Platform));
            MetaRow(sb, "Unity Version", Esc(report.Session.UnityVersion));
            MetaRow(sb, "Duration", $"{duration:F1}s");
            MetaRow(sb, "Environment", report.Session.IsEditor ? "Editor" : "Build");
            sb.Append("</table>\n</div>\n");

            // Grade summary
            AppendGradeSummary(sb, report);

            // Metrics table
            AppendMetricsTable(sb, report);

            // SVG charts
            var frames = session.GetFrames();
            if (frames.Length > 0)
            {
                AppendFrameTimeChart(sb, frames, report.Session.TargetFrameRate);
                AppendMemoryChart(sb, frames);
            }

            // Synthesis (deterministic insights)
            AppendSynthesis(sb, report);

            // Findings
            AppendFindings(sb, report);

            // Footer
            sb.Append("<div class=\"footer\">Generated by DrWario v3.0</div>\n");
            sb.Append("</body>\n</html>");

            return sb.ToString();
        }

        private static void AppendStyles(StringBuilder sb)
        {
            sb.Append(@"<style>
body {
  font-family: system-ui, -apple-system, sans-serif;
  background: #1a1a2e;
  color: #e0e0e0;
  max-width: 960px;
  margin: 0 auto;
  padding: 24px;
  line-height: 1.5;
}
h1 { color: #fff; margin-bottom: 8px; }
h2 { color: #ccc; border-bottom: 1px solid #333; padding-bottom: 8px; margin-top: 32px; }
.header { margin-bottom: 24px; }
.meta-table { border-collapse: collapse; margin-top: 12px; }
.meta-table td { padding: 4px 16px 4px 0; color: #aaa; }
.meta-table td:first-child { color: #888; }
.grade-section { text-align: center; margin: 32px 0; }
.grade-overall {
  display: inline-block;
  font-size: 96px;
  font-weight: bold;
  line-height: 1;
}
.grade-score { font-size: 20px; color: #aaa; margin-top: 4px; }
.category-grades { margin-top: 20px; }
.cat-grade {
  display: inline-block;
  text-align: center;
  margin: 8px 12px;
  padding: 12px 20px;
  background: #16213e;
  border-radius: 8px;
  min-width: 80px;
}
.cat-grade-letter { font-size: 36px; font-weight: bold; }
.cat-grade-label { font-size: 12px; color: #888; margin-top: 4px; }
.grade-A { color: #4CAF50; }
.grade-B { color: #2196F3; }
.grade-C { color: #FFC107; }
.grade-D { color: #FF9800; }
.grade-F { color: #F44336; }
table.metrics {
  width: 100%;
  border-collapse: collapse;
  margin-top: 12px;
}
table.metrics th, table.metrics td {
  padding: 8px 12px;
  text-align: left;
  border: 1px solid #2a2a4a;
}
table.metrics th { background: #16213e; color: #aaa; }
table.metrics tr:nth-child(even) { background: #1f1f3a; }
table.metrics tr:nth-child(odd) { background: #1a1a2e; }
.finding-card {
  border-radius: 8px;
  padding: 16px;
  margin: 12px 0;
  background: #16213e;
  border-left: 4px solid #2196F3;
}
.finding-card.severity-Critical { border-left-color: #F44336; }
.finding-card.severity-Warning { border-left-color: #FFC107; }
.finding-card.severity-Info { border-left-color: #2196F3; }
.finding-title { font-size: 16px; font-weight: bold; color: #fff; margin-bottom: 8px; }
.finding-desc { color: #bbb; margin-bottom: 8px; }
.finding-rec { color: #8bc; font-style: italic; margin-bottom: 8px; }
.finding-meta { font-size: 12px; color: #888; }
.badge {
  display: inline-block;
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 12px;
  font-weight: bold;
  color: #fff;
  margin-right: 8px;
  vertical-align: middle;
}
.badge-Critical { background: #F44336; }
.badge-Warning { background: #FFC107; color: #000; }
.badge-Info { background: #2196F3; }
.badge-confidence {
  display: inline-block;
  padding: 2px 6px;
  border-radius: 4px;
  font-size: 11px;
  color: #aaa;
  background: #2a2a4a;
  margin-left: 4px;
  vertical-align: middle;
}
.chart-container { margin: 24px 0; }
.chart-container h2 { margin-bottom: 12px; }
svg.chart {
  width: 100%;
  height: auto;
  background: #16213e;
  border-radius: 8px;
}
.synthesis { margin: 24px 0; }
.executive-summary {
  font-size: 15px;
  color: #bcd;
  background: #16213e;
  border-left: 4px solid #4488cc;
  padding: 16px;
  border-radius: 4px;
  line-height: 1.6;
}
.synthesis h3 { color: #bbb; margin-top: 20px; }
.synthesis ol { padding-left: 24px; }
.synthesis ol li { margin-bottom: 6px; color: #ccc; }
.finding-card.critical { border-left-color: #F44336; }
.finding-card.warning { border-left-color: #FFC107; }
.finding-card.info { border-left-color: #2196F3; }
.footer {
  text-align: center;
  color: #555;
  font-size: 12px;
  margin-top: 48px;
  padding-top: 16px;
  border-top: 1px solid #2a2a4a;
}
</style>
");
        }

        private static void MetaRow(StringBuilder sb, string label, string value)
        {
            sb.Append("<tr><td>").Append(Esc(label)).Append("</td><td>").Append(value).Append("</td></tr>\n");
        }

        private static void AppendGradeSummary(StringBuilder sb, DiagnosticReport report)
        {
            sb.Append("<div class=\"grade-section\">\n");
            sb.Append("<div class=\"grade-overall grade-").Append(report.OverallGrade).Append("\">");
            sb.Append(report.OverallGrade);
            sb.Append("</div>\n");
            sb.Append("<div class=\"grade-score\">").Append($"{report.HealthScore:F0} / 100").Append("</div>\n");

            if (report.CategoryGrades.Count > 0)
            {
                sb.Append("<div class=\"category-grades\">\n");
                foreach (var kv in report.CategoryGrades)
                {
                    sb.Append("<div class=\"cat-grade\">");
                    sb.Append("<div class=\"cat-grade-letter grade-").Append(kv.Value).Append("\">").Append(kv.Value).Append("</div>");
                    sb.Append("<div class=\"cat-grade-label\">").Append(Esc(kv.Key)).Append("</div>");
                    sb.Append("</div>\n");
                }
                sb.Append("</div>\n");
            }

            sb.Append("</div>\n");
        }

        private static void AppendMetricsTable(StringBuilder sb, DiagnosticReport report)
        {
            sb.Append("<h2>Performance Metrics</h2>\n");
            sb.Append("<table class=\"metrics\">\n");
            sb.Append("<tr><th>Metric</th><th>Value</th></tr>\n");
            MRow(sb, "Avg CPU Time", $"{report.AvgCpuTimeMs:F2} ms");
            MRow(sb, "P95 CPU Time", $"{report.P95CpuTimeMs:F2} ms");
            MRow(sb, "P99 CPU Time", $"{report.P99CpuTimeMs:F2} ms");
            MRow(sb, "Avg GC Alloc", $"{report.AvgGcAllocBytes:F0} bytes/frame");
            MRow(sb, "Avg Draw Calls", $"{report.AvgDrawCalls:F0}");
            MRow(sb, "Memory Slope", $"{report.MemorySlope:F2} bytes/frame");
            sb.Append("</table>\n");
        }

        private static void MRow(StringBuilder sb, string metric, string value)
        {
            sb.Append("<tr><td>").Append(Esc(metric)).Append("</td><td>").Append(Esc(value)).Append("</td></tr>\n");
        }

        private static void AppendSynthesis(StringBuilder sb, DiagnosticReport report)
        {
            if (!report.Synthesis.HasValue) return;
            var syn = report.Synthesis.Value;

            sb.Append("<div class=\"synthesis\">\n");

            if (!string.IsNullOrEmpty(syn.ExecutiveSummary))
            {
                sb.Append("<h2>Summary</h2>\n");
                sb.Append("<p class=\"executive-summary\">").Append(Esc(syn.ExecutiveSummary)).Append("</p>\n");
            }

            if (syn.Correlations != null && syn.Correlations.Count > 0)
            {
                sb.Append("<h3>Insights</h3>\n");
                foreach (var c in syn.Correlations)
                {
                    string sevClass = c.Severity == Severity.Critical ? "critical"
                        : c.Severity == Severity.Warning ? "warning" : "info";
                    sb.Append("<div class=\"finding-card ").Append(sevClass).Append("\">\n");
                    sb.Append("<div class=\"finding-title\">").Append(Esc(c.Title)).Append("</div>\n");
                    sb.Append("<div class=\"finding-desc\">").Append(Esc(c.Description)).Append("</div>\n");
                    sb.Append("<div class=\"finding-rec\">").Append(Esc(c.Recommendation)).Append("</div>\n");
                    sb.Append("</div>\n");
                }
            }

            if (syn.PrioritizedActions != null && syn.PrioritizedActions.Count > 0)
            {
                sb.Append("<h3>Prioritized Actions</h3>\n<ol>\n");
                foreach (var a in syn.PrioritizedActions)
                {
                    sb.Append("<li><strong>[").Append(Esc(a.ExpectedImpact)).Append("]</strong> ");
                    sb.Append(Esc(a.Action)).Append("</li>\n");
                }
                sb.Append("</ol>\n");
            }

            sb.Append("</div>\n");
        }

        private static void AppendFindings(StringBuilder sb, DiagnosticReport report)
        {
            sb.Append("<h2>Findings</h2>\n");

            var sorted = report.Findings.OrderByDescending(f => f.Severity).ToList();
            if (sorted.Count == 0)
            {
                sb.Append("<p>No findings detected. Your project looks healthy!</p>\n");
                return;
            }

            foreach (var f in sorted)
            {
                var sev = f.Severity.ToString();
                sb.Append("<div class=\"finding-card severity-").Append(sev).Append("\">\n");

                // Title line with badges
                sb.Append("<div class=\"finding-title\">");
                sb.Append("<span class=\"badge badge-").Append(sev).Append("\">").Append(sev).Append("</span>");
                sb.Append(Esc(f.Title));
                if (f.Confidence != Confidence.High)
                    sb.Append("<span class=\"badge-confidence\">").Append(f.Confidence).Append(" confidence</span>");
                sb.Append("</div>\n");

                // Description
                sb.Append("<div class=\"finding-desc\">").Append(Esc(f.Description)).Append("</div>\n");

                // Recommendation
                if (!string.IsNullOrEmpty(f.Recommendation))
                    sb.Append("<div class=\"finding-rec\">").Append(Esc(f.Recommendation)).Append("</div>\n");

                // Metadata
                var metaParts = new List<string>();
                if (f.Metric != 0 || f.Threshold != 0)
                    metaParts.Add($"Metric: {f.Metric:F2} (threshold: {f.Threshold:F2})");
                if (!string.IsNullOrEmpty(f.ScriptPath))
                {
                    var script = f.ScriptPath;
                    if (f.ScriptLine > 0) script += $":{f.ScriptLine}";
                    metaParts.Add($"Script: {script}");
                }
                if (!string.IsNullOrEmpty(f.AssetPath))
                    metaParts.Add($"Asset: {f.AssetPath}");
                if (!string.IsNullOrEmpty(f.EnvironmentNote))
                    metaParts.Add(f.EnvironmentNote);

                if (metaParts.Count > 0)
                {
                    sb.Append("<div class=\"finding-meta\">");
                    sb.Append(Esc(string.Join(" | ", metaParts)));
                    sb.Append("</div>\n");
                }

                sb.Append("</div>\n");
            }
        }

        private static void AppendFrameTimeChart(StringBuilder sb, FrameSample[] frames, int targetFrameRate)
        {
            const int svgW = 600;
            const int svgH = 200;
            const int padL = 50;
            const int padR = 10;
            const int padT = 20;
            const int padB = 30;
            int plotW = svgW - padL - padR;
            int plotH = svgH - padT - padB;

            var values = Downsample(frames.Select(f => (double)f.CpuFrameTimeMs).ToArray(), 200);
            if (values.Length == 0) return;

            double maxVal = values.Max();
            float targetMs = targetFrameRate > 0 ? 1000f / targetFrameRate : 16.67f;
            if (maxVal < targetMs * 1.2) maxVal = targetMs * 1.5;

            sb.Append("<div class=\"chart-container\">\n<h2>Frame Time (CPU)</h2>\n");
            sb.Append($"<svg class=\"chart\" viewBox=\"0 0 {svgW} {svgH}\" preserveAspectRatio=\"xMidYMid meet\">\n");

            // Grid lines
            AppendGridLines(sb, padL, padT, plotW, plotH, maxVal, "ms");

            // Target frame time reference line
            double targetY = padT + plotH - (targetMs / maxVal * plotH);
            sb.Append($"<line x1=\"{padL}\" y1=\"{F(targetY)}\" x2=\"{padL + plotW}\" y2=\"{F(targetY)}\" stroke=\"#F44336\" stroke-width=\"1\" stroke-dasharray=\"4,4\" />\n");
            sb.Append($"<text x=\"{padL + plotW + 2}\" y=\"{F(targetY + 4)}\" fill=\"#F44336\" font-size=\"9\">{targetMs:F1}ms</text>\n");

            // Polyline
            var points = new StringBuilder();
            for (int i = 0; i < values.Length; i++)
            {
                double x = padL + (double)i / (values.Length - 1) * plotW;
                double y = padT + plotH - (values[i] / maxVal * plotH);
                if (i > 0) points.Append(' ');
                points.Append(F(x)).Append(',').Append(F(y));
            }
            sb.Append($"<polyline points=\"{points}\" fill=\"none\" stroke=\"#4CAF50\" stroke-width=\"1.5\" />\n");

            // X axis label
            sb.Append($"<text x=\"{svgW / 2}\" y=\"{svgH - 2}\" fill=\"#888\" font-size=\"10\" text-anchor=\"middle\">Frames</text>\n");

            sb.Append("</svg>\n</div>\n");
        }

        private static void AppendMemoryChart(StringBuilder sb, FrameSample[] frames)
        {
            const int svgW = 600;
            const int svgH = 200;
            const int padL = 60;
            const int padR = 10;
            const int padT = 20;
            const int padB = 30;
            int plotW = svgW - padL - padR;
            int plotH = svgH - padT - padB;

            var rawValues = frames.Select(f => (double)f.TotalHeapBytes).ToArray();
            // Skip if all zeros
            if (rawValues.All(v => v == 0)) return;

            var values = Downsample(rawValues, 200);
            if (values.Length == 0) return;

            double maxVal = values.Max();
            double minVal = values.Min();
            if (maxVal <= minVal) maxVal = minVal + 1;

            // Use MB for axis labels
            double range = maxVal - minVal;

            sb.Append("<div class=\"chart-container\">\n<h2>Heap Memory</h2>\n");
            sb.Append($"<svg class=\"chart\" viewBox=\"0 0 {svgW} {svgH}\" preserveAspectRatio=\"xMidYMid meet\">\n");

            // Grid lines (memory-specific)
            int gridLines = 4;
            for (int i = 0; i <= gridLines; i++)
            {
                double frac = (double)i / gridLines;
                double y = padT + plotH - frac * plotH;
                double val = minVal + frac * range;
                string label = FormatBytes(val);
                sb.Append($"<line x1=\"{padL}\" y1=\"{F(y)}\" x2=\"{padL + plotW}\" y2=\"{F(y)}\" stroke=\"#2a2a4a\" stroke-width=\"1\" />\n");
                sb.Append($"<text x=\"{padL - 4}\" y=\"{F(y + 4)}\" fill=\"#888\" font-size=\"9\" text-anchor=\"end\">{label}</text>\n");
            }

            // Polyline
            var points = new StringBuilder();
            for (int i = 0; i < values.Length; i++)
            {
                double x = padL + (double)i / (values.Length - 1) * plotW;
                double y = padT + plotH - ((values[i] - minVal) / range * plotH);
                if (i > 0) points.Append(' ');
                points.Append(F(x)).Append(',').Append(F(y));
            }
            sb.Append($"<polyline points=\"{points}\" fill=\"none\" stroke=\"#2196F3\" stroke-width=\"1.5\" />\n");

            // X axis label
            sb.Append($"<text x=\"{svgW / 2}\" y=\"{svgH - 2}\" fill=\"#888\" font-size=\"10\" text-anchor=\"middle\">Frames</text>\n");

            sb.Append("</svg>\n</div>\n");
        }

        private static void AppendGridLines(StringBuilder sb, int padL, int padT, int plotW, int plotH, double maxVal, string unit)
        {
            int gridLines = 4;
            for (int i = 0; i <= gridLines; i++)
            {
                double frac = (double)i / gridLines;
                double y = padT + plotH - frac * plotH;
                double val = frac * maxVal;
                sb.Append($"<line x1=\"{padL}\" y1=\"{F(y)}\" x2=\"{padL + plotW}\" y2=\"{F(y)}\" stroke=\"#2a2a4a\" stroke-width=\"1\" />\n");
                sb.Append($"<text x=\"{padL - 4}\" y=\"{F(y + 4)}\" fill=\"#888\" font-size=\"9\" text-anchor=\"end\">{val:F1}{unit}</text>\n");
            }
        }

        private static double[] Downsample(double[] data, int maxPoints)
        {
            if (data.Length <= maxPoints) return data;

            var result = new double[maxPoints];
            double step = (double)data.Length / maxPoints;
            for (int i = 0; i < maxPoints; i++)
            {
                int start = (int)(i * step);
                int end = (int)((i + 1) * step);
                if (end > data.Length) end = data.Length;
                if (end <= start) end = start + 1;

                // Take the max in each bucket to preserve spikes
                double max = data[start];
                for (int j = start + 1; j < end; j++)
                {
                    if (data[j] > max) max = data[j];
                }
                result[i] = max;
            }
            return result;
        }

        private static string FormatBytes(double bytes)
        {
            if (bytes >= 1024 * 1024 * 1024) return $"{bytes / (1024 * 1024 * 1024):F1} GB";
            if (bytes >= 1024 * 1024) return $"{bytes / (1024 * 1024):F1} MB";
            if (bytes >= 1024) return $"{bytes / 1024:F0} KB";
            return $"{bytes:F0} B";
        }

        private static string F(double value)
        {
            return value.ToString("F1", CultureInfo.InvariantCulture);
        }

        private static string Esc(string text)
        {
            if (string.IsNullOrEmpty(text)) return "";
            return text
                .Replace("&", "&amp;")
                .Replace("<", "&lt;")
                .Replace(">", "&gt;")
                .Replace("\"", "&quot;");
        }
    }
}
